version: '3'
services:
  db:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3001:3306"
  web:
    build: .
    command: bash -c "npm start"
    restart: always
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    user: "${UID}:${GID}"
